package org.redcross.sar.mso.data;

import org.redcross.sar.mso.IMsoManagerIf;
import org.redcross.sar.mso.IMsoModelIf;
import org.redcross.sar.util.except.MsoCastException;

import java.util.Calendar;
import java.util.Collection;

public class EventImpl extends AbstractTimeItem implements IEventIf
{

    private final AttributeImpl.MsoInteger m_number = new AttributeImpl.MsoInteger(this, "Number",true);

    /**
     * List of tasks generated by this event
     */
    private final TaskListImpl m_eventTasks = new TaskListImpl(this, "EventTasks", false);

    public EventImpl(IMsoObjectIf.IObjectIdIf anObjectId, int aNumber)
    {
        super(anObjectId);
        setNumber(aNumber);
    }

    public EventImpl(IMsoObjectIf.IObjectIdIf anObjectId, int aNumber, Calendar aCalendar)
    {
        super(anObjectId, aCalendar);
        setNumber(aNumber);
    }

    @Override
    protected void defineAttributes()
    {
        super.defineAttributes();
        addAttribute(m_number);
    }

    @Override
    protected void defineLists()
    {
        super.defineLists();
        addList(m_eventTasks);
    }

    @Override
    protected void defineReferences()
    {
        super.defineReferences();
    }


    @Override
    public boolean addObjectReference(IMsoObjectIf anObject, String aReferenceName)
    {
        if (anObject instanceof ITaskIf)
        {
            m_eventTasks.add((ITaskIf)anObject);
            return true;
        }
        return super.addObjectReference(anObject,aReferenceName);

    }

    @Override
    public boolean removeObjectReference(IMsoObjectIf anObject, String aReferenceName)
    {
        if (anObject instanceof ITaskIf)
        {
            return m_eventTasks.removeReference((ITaskIf) anObject);
        }
        return super.removeObjectReference(anObject,aReferenceName);
    }

    public static EventImpl implementationOf(IEventIf anInterface) throws MsoCastException
    {
        try
        {
            return (EventImpl) anInterface;
        }
        catch (ClassCastException e)
        {
            throw new MsoCastException("Illegal cast to EventImpl");
        }
    }

    public IMsoManagerIf.MsoClassCode getMsoClassCode()
    {
        return IMsoManagerIf.MsoClassCode.CLASSCODE_EVENT;
    }

    /*-------------------------------------------------------------------------------------------
    * Methods for attributes
    *-------------------------------------------------------------------------------------------*/
    // From ISerialNumberedIf
    public void setNumber(int aNumber)
    {
        m_number.setValue(aNumber);
    }

    public int getNumber()
    {
        return m_number.intValue();
    }

    public IMsoModelIf.ModificationState getNumberState()
    {
        return m_number.getState();
    }

    public IAttributeIf.IMsoIntegerIf getNumberAttribute()
    {
        return m_number;
    }

    /*-------------------------------------------------------------------------------------------
    * Methods for lists
    *-------------------------------------------------------------------------------------------*/

    public void addEventTask(ITaskIf anITaskIf)
    {
        m_eventTasks.add(anITaskIf);
    }

    public ITaskListIf getEventTasks()
    {
        return m_eventTasks;
    }

    public IMsoModelIf.ModificationState getEventTasksState(ITaskIf anITaskIf)
    {
        return m_eventTasks.getState(anITaskIf);
    }

    public Collection<ITaskIf> getEventTasksItems()
    {
        return m_eventTasks.getItems();
    }

    /*-------------------------------------------------------------------------------------------
    * Other specified methods
    *-------------------------------------------------------------------------------------------*/

    public Calendar getEventTime()
    {
        return getTimeStamp();
    }

    public void setEventTime(Calendar aCalendar)
    {
        setTimeStamp(aCalendar);
    }


    public IMsoModelIf.ModificationState getEventTimeState()
    {
        return getTimeStampState();
    }
}