package org.redcross.sar.mso.data;

import org.redcross.sar.mso.IMsoManagerIf;
import org.redcross.sar.util.except.MsoCastException;

import java.util.Calendar;

public class EventImpl extends AbstractTimeItem implements IEventIf
{

    /**
     * List of tasks generated by this event
     */
    private final TaskListImpl m_createdTasks = new TaskListImpl(this, "CreatedTasks", true);

    public EventImpl(IMsoObjectIf.IObjectIdIf anObjectId, Calendar aCalendar)
    {
        super(anObjectId, aCalendar);
    }

    protected void defineAttributes()
    {
        super.defineAttributes();
    }

    protected void defineLists()
    {
        super.defineLists();
        addList(m_createdTasks);
    }

    protected void defineReferences()
    {
        super.defineReferences();
    }

    public static EventImpl implementationOf(IEventIf anInterface) throws MsoCastException
    {
        try
        {
            return (EventImpl) anInterface;
        }
        catch (ClassCastException e)
        {
            throw new MsoCastException("Illegal cast to EventImpl");
        }
    }

    public IMsoManagerIf.MsoClassCode getMsoClassCode()
    {
        return IMsoManagerIf.MsoClassCode.CLASSCODE_EVENT;
    }
}